FROM debian:bookworm-slim

RUN groupadd --system --gid 10001 edgepilot \
    && useradd --system --uid 10001 --gid edgepilot --home-dir /var/lib/edge-pilot --create-home --shell /usr/sbin/nologin edgepilot

WORKDIR /var/lib/edge-pilot

ARG TARGETPLATFORM

COPY --chown=edgepilot:edgepilot ${TARGETPLATFORM}/edge-pilot-control /usr/local/bin/edge-pilot-control

USER edgepilot:edgepilot

ENTRYPOINT ["/usr/local/bin/edge-pilot-control"]
