// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/shared/grpcapi/agent_control.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Slot int32

const (
	Slot_SLOT_UNSPECIFIED Slot = 0
	Slot_SLOT_BLUE        Slot = 1
	Slot_SLOT_GREEN       Slot = 2
)

// Enum value maps for Slot.
var (
	Slot_name = map[int32]string{
		0: "SLOT_UNSPECIFIED",
		1: "SLOT_BLUE",
		2: "SLOT_GREEN",
	}
	Slot_value = map[string]int32{
		"SLOT_UNSPECIFIED": 0,
		"SLOT_BLUE":        1,
		"SLOT_GREEN":       2,
	}
)

func (x Slot) Enum() *Slot {
	p := new(Slot)
	*p = x
	return p
}

func (x Slot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Slot) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_shared_grpcapi_agent_control_proto_enumTypes[0].Descriptor()
}

func (Slot) Type() protoreflect.EnumType {
	return &file_internal_shared_grpcapi_agent_control_proto_enumTypes[0]
}

func (x Slot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Slot.Descriptor instead.
func (Slot) EnumDescriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{0}
}

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED    TaskType = 0
	TaskType_TASK_TYPE_DEPLOY_GREEN   TaskType = 1
	TaskType_TASK_TYPE_SWITCH_TRAFFIC TaskType = 2
	TaskType_TASK_TYPE_ROLLBACK       TaskType = 3
	TaskType_TASK_TYPE_CLEANUP_OLD    TaskType = 4
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_DEPLOY_GREEN",
		2: "TASK_TYPE_SWITCH_TRAFFIC",
		3: "TASK_TYPE_ROLLBACK",
		4: "TASK_TYPE_CLEANUP_OLD",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED":    0,
		"TASK_TYPE_DEPLOY_GREEN":   1,
		"TASK_TYPE_SWITCH_TRAFFIC": 2,
		"TASK_TYPE_ROLLBACK":       3,
		"TASK_TYPE_CLEANUP_OLD":    4,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_shared_grpcapi_agent_control_proto_enumTypes[1].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_internal_shared_grpcapi_agent_control_proto_enumTypes[1]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{1}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 1
	TaskStatus_TASK_STATUS_SUCCEEDED   TaskStatus = 2
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_RUNNING",
		2: "TASK_STATUS_SUCCEEDED",
		3: "TASK_STATUS_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_RUNNING":     1,
		"TASK_STATUS_SUCCEEDED":   2,
		"TASK_STATUS_FAILED":      3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_shared_grpcapi_agent_control_proto_enumTypes[2].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_internal_shared_grpcapi_agent_control_proto_enumTypes[2]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{2}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_TaskUpdate
	//	*AgentMessage_Stats
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *HelloMessage {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *HeartbeatMessage {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskUpdate() *TaskUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskUpdate); ok {
			return x.TaskUpdate
		}
	}
	return nil
}

func (x *AgentMessage) GetStats() *StatsReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *HelloMessage `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *HeartbeatMessage `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_TaskUpdate struct {
	TaskUpdate *TaskUpdate `protobuf:"bytes,3,opt,name=task_update,json=taskUpdate,proto3,oneof"`
}

type AgentMessage_Stats struct {
	Stats *StatsReport `protobuf:"bytes,4,opt,name=stats,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_TaskUpdate) isAgentMessage_Payload() {}

func (*AgentMessage_Stats) isAgentMessage_Payload() {}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Ack
	//	*ControlMessage_Task
	//	*ControlMessage_ProxyConfig
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetAck() *AckMessage {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControlMessage) GetTask() *TaskCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *ControlMessage) GetProxyConfig() *ProxyConfigSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ProxyConfig); ok {
			return x.ProxyConfig
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Ack struct {
	Ack *AckMessage `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ControlMessage_Task struct {
	Task *TaskCommand `protobuf:"bytes,2,opt,name=task,proto3,oneof"`
}

type ControlMessage_ProxyConfig struct {
	ProxyConfig *ProxyConfigSnapshot `protobuf:"bytes,3,opt,name=proxy_config,json=proxyConfig,proto3,oneof"`
}

func (*ControlMessage_Ack) isControlMessage_Payload() {}

func (*ControlMessage_Task) isControlMessage_Payload() {}

func (*ControlMessage_ProxyConfig) isControlMessage_Payload() {}

type HelloMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloMessage) Reset() {
	*x = HelloMessage{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloMessage) ProtoMessage() {}

func (x *HelloMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloMessage.ProtoReflect.Descriptor instead.
func (*HelloMessage) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{2}
}

func (x *HelloMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HelloMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HelloMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloMessage) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HelloMessage) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HeartbeatMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RunningTaskIds []string               `protobuf:"bytes,2,rep,name=running_task_ids,json=runningTaskIds,proto3" json:"running_task_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatMessage) GetRunningTaskIds() []string {
	if x != nil {
		return x.RunningTaskIds
	}
	return nil
}

type AckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{4}
}

func (x *AckMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{5}
}

func (x *VolumeMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *VolumeMount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type TaskCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ReleaseId         string                 `protobuf:"bytes,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ServiceId         string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceKey        string                 `protobuf:"bytes,4,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"`
	AgentId           string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type              TaskType               `protobuf:"varint,6,opt,name=type,proto3,enum=edgepilot.grpcapi.TaskType" json:"type,omitempty"`
	ImageRepo         string                 `protobuf:"bytes,7,opt,name=image_repo,json=imageRepo,proto3" json:"image_repo,omitempty"`
	ImageTag          string                 `protobuf:"bytes,8,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	CommitSha         string                 `protobuf:"bytes,9,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	TraceId           string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TargetSlot        Slot                   `protobuf:"varint,11,opt,name=target_slot,json=targetSlot,proto3,enum=edgepilot.grpcapi.Slot" json:"target_slot,omitempty"`
	CurrentLiveSlot   Slot                   `protobuf:"varint,12,opt,name=current_live_slot,json=currentLiveSlot,proto3,enum=edgepilot.grpcapi.Slot" json:"current_live_slot,omitempty"`
	ContainerPort     int32                  `protobuf:"varint,13,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	HostPort          int32                  `protobuf:"varint,14,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	HttpHealthPath    string                 `protobuf:"bytes,15,opt,name=http_health_path,json=httpHealthPath,proto3" json:"http_health_path,omitempty"`
	HttpExpectedCode  int32                  `protobuf:"varint,16,opt,name=http_expected_code,json=httpExpectedCode,proto3" json:"http_expected_code,omitempty"`
	HttpTimeoutSecond int32                  `protobuf:"varint,17,opt,name=http_timeout_second,json=httpTimeoutSecond,proto3" json:"http_timeout_second,omitempty"`
	BackendName       string                 `protobuf:"bytes,18,opt,name=backend_name,json=backendName,proto3" json:"backend_name,omitempty"`
	ServerName        string                 `protobuf:"bytes,19,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	PreviousServer    string                 `protobuf:"bytes,20,opt,name=previous_server,json=previousServer,proto3" json:"previous_server,omitempty"`
	Env               map[string]string      `protobuf:"bytes,21,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command           []string               `protobuf:"bytes,22,rep,name=command,proto3" json:"command,omitempty"`
	Entrypoint        []string               `protobuf:"bytes,23,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Volumes           []*VolumeMount         `protobuf:"bytes,24,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskCommand) Reset() {
	*x = TaskCommand{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCommand) ProtoMessage() {}

func (x *TaskCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCommand.ProtoReflect.Descriptor instead.
func (*TaskCommand) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{6}
}

func (x *TaskCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCommand) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *TaskCommand) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *TaskCommand) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

func (x *TaskCommand) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskCommand) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *TaskCommand) GetImageRepo() string {
	if x != nil {
		return x.ImageRepo
	}
	return ""
}

func (x *TaskCommand) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *TaskCommand) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *TaskCommand) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TaskCommand) GetTargetSlot() Slot {
	if x != nil {
		return x.TargetSlot
	}
	return Slot_SLOT_UNSPECIFIED
}

func (x *TaskCommand) GetCurrentLiveSlot() Slot {
	if x != nil {
		return x.CurrentLiveSlot
	}
	return Slot_SLOT_UNSPECIFIED
}

func (x *TaskCommand) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *TaskCommand) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *TaskCommand) GetHttpHealthPath() string {
	if x != nil {
		return x.HttpHealthPath
	}
	return ""
}

func (x *TaskCommand) GetHttpExpectedCode() int32 {
	if x != nil {
		return x.HttpExpectedCode
	}
	return 0
}

func (x *TaskCommand) GetHttpTimeoutSecond() int32 {
	if x != nil {
		return x.HttpTimeoutSecond
	}
	return 0
}

func (x *TaskCommand) GetBackendName() string {
	if x != nil {
		return x.BackendName
	}
	return ""
}

func (x *TaskCommand) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TaskCommand) GetPreviousServer() string {
	if x != nil {
		return x.PreviousServer
	}
	return ""
}

func (x *TaskCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TaskCommand) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TaskCommand) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *TaskCommand) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type TaskUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=edgepilot.grpcapi.TaskStatus" json:"status,omitempty"`
	Step          string                 `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ContainerId   string                 `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ListenAddress string                 `protobuf:"bytes,6,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	Slot          Slot                   `protobuf:"varint,7,opt,name=slot,proto3,enum=edgepilot.grpcapi.Slot" json:"slot,omitempty"`
	ServerName    string                 `protobuf:"bytes,8,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Metrics       map[string]int64       `protobuf:"bytes,9,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdate) Reset() {
	*x = TaskUpdate{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdate) ProtoMessage() {}

func (x *TaskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdate.ProtoReflect.Descriptor instead.
func (*TaskUpdate) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{7}
}

func (x *TaskUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskUpdate) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskUpdate) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *TaskUpdate) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskUpdate) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *TaskUpdate) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *TaskUpdate) GetSlot() Slot {
	if x != nil {
		return x.Slot
	}
	return Slot_SLOT_UNSPECIFIED
}

func (x *TaskUpdate) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TaskUpdate) GetMetrics() map[string]int64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ProxyServiceConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceKey      string                 `protobuf:"bytes,2,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"`
	RouteHost       string                 `protobuf:"bytes,3,opt,name=route_host,json=routeHost,proto3" json:"route_host,omitempty"`
	RoutePathPrefix string                 `protobuf:"bytes,4,opt,name=route_path_prefix,json=routePathPrefix,proto3" json:"route_path_prefix,omitempty"`
	BackendName     string                 `protobuf:"bytes,5,opt,name=backend_name,json=backendName,proto3" json:"backend_name,omitempty"`
	BlueServerName  string                 `protobuf:"bytes,6,opt,name=blue_server_name,json=blueServerName,proto3" json:"blue_server_name,omitempty"`
	GreenServerName string                 `protobuf:"bytes,7,opt,name=green_server_name,json=greenServerName,proto3" json:"green_server_name,omitempty"`
	BlueHostPort    int32                  `protobuf:"varint,8,opt,name=blue_host_port,json=blueHostPort,proto3" json:"blue_host_port,omitempty"`
	GreenHostPort   int32                  `protobuf:"varint,9,opt,name=green_host_port,json=greenHostPort,proto3" json:"green_host_port,omitempty"`
	CurrentLiveSlot Slot                   `protobuf:"varint,10,opt,name=current_live_slot,json=currentLiveSlot,proto3,enum=edgepilot.grpcapi.Slot" json:"current_live_slot,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProxyServiceConfig) Reset() {
	*x = ProxyServiceConfig{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyServiceConfig) ProtoMessage() {}

func (x *ProxyServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyServiceConfig.ProtoReflect.Descriptor instead.
func (*ProxyServiceConfig) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{8}
}

func (x *ProxyServiceConfig) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ProxyServiceConfig) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

func (x *ProxyServiceConfig) GetRouteHost() string {
	if x != nil {
		return x.RouteHost
	}
	return ""
}

func (x *ProxyServiceConfig) GetRoutePathPrefix() string {
	if x != nil {
		return x.RoutePathPrefix
	}
	return ""
}

func (x *ProxyServiceConfig) GetBackendName() string {
	if x != nil {
		return x.BackendName
	}
	return ""
}

func (x *ProxyServiceConfig) GetBlueServerName() string {
	if x != nil {
		return x.BlueServerName
	}
	return ""
}

func (x *ProxyServiceConfig) GetGreenServerName() string {
	if x != nil {
		return x.GreenServerName
	}
	return ""
}

func (x *ProxyServiceConfig) GetBlueHostPort() int32 {
	if x != nil {
		return x.BlueHostPort
	}
	return 0
}

func (x *ProxyServiceConfig) GetGreenHostPort() int32 {
	if x != nil {
		return x.GreenHostPort
	}
	return 0
}

func (x *ProxyServiceConfig) GetCurrentLiveSlot() Slot {
	if x != nil {
		return x.CurrentLiveSlot
	}
	return Slot_SLOT_UNSPECIFIED
}

type ProxyConfigSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	FrontendName   string                 `protobuf:"bytes,2,opt,name=frontend_name,json=frontendName,proto3" json:"frontend_name,omitempty"`
	DefaultBackend string                 `protobuf:"bytes,3,opt,name=default_backend,json=defaultBackend,proto3" json:"default_backend,omitempty"`
	BindPort       int32                  `protobuf:"varint,4,opt,name=bind_port,json=bindPort,proto3" json:"bind_port,omitempty"`
	Services       []*ProxyServiceConfig  `protobuf:"bytes,5,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProxyConfigSnapshot) Reset() {
	*x = ProxyConfigSnapshot{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfigSnapshot) ProtoMessage() {}

func (x *ProxyConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ProxyConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{9}
}

func (x *ProxyConfigSnapshot) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ProxyConfigSnapshot) GetFrontendName() string {
	if x != nil {
		return x.FrontendName
	}
	return ""
}

func (x *ProxyConfigSnapshot) GetDefaultBackend() string {
	if x != nil {
		return x.DefaultBackend
	}
	return ""
}

func (x *ProxyConfigSnapshot) GetBindPort() int32 {
	if x != nil {
		return x.BindPort
	}
	return 0
}

func (x *ProxyConfigSnapshot) GetServices() []*ProxyServiceConfig {
	if x != nil {
		return x.Services
	}
	return nil
}

type BackendStatPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BackendName   string                 `protobuf:"bytes,2,opt,name=backend_name,json=backendName,proto3" json:"backend_name,omitempty"`
	ServerName    string                 `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Scur          int64                  `protobuf:"varint,4,opt,name=scur,proto3" json:"scur,omitempty"`
	Rate          int64                  `protobuf:"varint,5,opt,name=rate,proto3" json:"rate,omitempty"`
	ErrorRequests int64                  `protobuf:"varint,6,opt,name=error_requests,json=errorRequests,proto3" json:"error_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendStatPoint) Reset() {
	*x = BackendStatPoint{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendStatPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendStatPoint) ProtoMessage() {}

func (x *BackendStatPoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendStatPoint.ProtoReflect.Descriptor instead.
func (*BackendStatPoint) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{10}
}

func (x *BackendStatPoint) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *BackendStatPoint) GetBackendName() string {
	if x != nil {
		return x.BackendName
	}
	return ""
}

func (x *BackendStatPoint) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *BackendStatPoint) GetScur() int64 {
	if x != nil {
		return x.Scur
	}
	return 0
}

func (x *BackendStatPoint) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *BackendStatPoint) GetErrorRequests() int64 {
	if x != nil {
		return x.ErrorRequests
	}
	return 0
}

type StatsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Services      []*BackendStatPoint    `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsReport) Reset() {
	*x = StatsReport{}
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReport) ProtoMessage() {}

func (x *StatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_agent_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReport.ProtoReflect.Descriptor instead.
func (*StatsReport) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP(), []int{11}
}

func (x *StatsReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatsReport) GetServices() []*BackendStatPoint {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_internal_shared_grpcapi_agent_control_proto protoreflect.FileDescriptor

const file_internal_shared_grpcapi_agent_control_proto_rawDesc = "" +
	"\n" +
	"+internal/shared/grpcapi/agent_control.proto\x12\x11edgepilot.grpcapi\"\x91\x02\n" +
	"\fAgentMessage\x127\n" +
	"\x05hello\x18\x01 \x01(\v2\x1f.edgepilot.grpcapi.HelloMessageH\x00R\x05hello\x12C\n" +
	"\theartbeat\x18\x02 \x01(\v2#.edgepilot.grpcapi.HeartbeatMessageH\x00R\theartbeat\x12@\n" +
	"\vtask_update\x18\x03 \x01(\v2\x1d.edgepilot.grpcapi.TaskUpdateH\x00R\n" +
	"taskUpdate\x126\n" +
	"\x05stats\x18\x04 \x01(\v2\x1e.edgepilot.grpcapi.StatsReportH\x00R\x05statsB\t\n" +
	"\apayload\"\xd1\x01\n" +
	"\x0eControlMessage\x121\n" +
	"\x03ack\x18\x01 \x01(\v2\x1d.edgepilot.grpcapi.AckMessageH\x00R\x03ack\x124\n" +
	"\x04task\x18\x02 \x01(\v2\x1e.edgepilot.grpcapi.TaskCommandH\x00R\x04task\x12K\n" +
	"\fproxy_config\x18\x03 \x01(\v2&.edgepilot.grpcapi.ProxyConfigSnapshotH\x00R\vproxyConfigB\t\n" +
	"\apayload\"\x99\x01\n" +
	"\fHelloMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"W\n" +
	"\x10HeartbeatMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12(\n" +
	"\x10running_task_ids\x18\x02 \x03(\tR\x0erunningTaskIds\"&\n" +
	"\n" +
	"AckMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Z\n" +
	"\vVolumeMount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\xe6\a\n" +
	"\vTaskCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\tR\treleaseId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vservice_key\x18\x04 \x01(\tR\n" +
	"serviceKey\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12/\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1b.edgepilot.grpcapi.TaskTypeR\x04type\x12\x1d\n" +
	"\n" +
	"image_repo\x18\a \x01(\tR\timageRepo\x12\x1b\n" +
	"\timage_tag\x18\b \x01(\tR\bimageTag\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\t \x01(\tR\tcommitSha\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x128\n" +
	"\vtarget_slot\x18\v \x01(\x0e2\x17.edgepilot.grpcapi.SlotR\n" +
	"targetSlot\x12C\n" +
	"\x11current_live_slot\x18\f \x01(\x0e2\x17.edgepilot.grpcapi.SlotR\x0fcurrentLiveSlot\x12%\n" +
	"\x0econtainer_port\x18\r \x01(\x05R\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x0e \x01(\x05R\bhostPort\x12(\n" +
	"\x10http_health_path\x18\x0f \x01(\tR\x0ehttpHealthPath\x12,\n" +
	"\x12http_expected_code\x18\x10 \x01(\x05R\x10httpExpectedCode\x12.\n" +
	"\x13http_timeout_second\x18\x11 \x01(\x05R\x11httpTimeoutSecond\x12!\n" +
	"\fbackend_name\x18\x12 \x01(\tR\vbackendName\x12\x1f\n" +
	"\vserver_name\x18\x13 \x01(\tR\n" +
	"serverName\x12'\n" +
	"\x0fprevious_server\x18\x14 \x01(\tR\x0epreviousServer\x129\n" +
	"\x03env\x18\x15 \x03(\v2'.edgepilot.grpcapi.TaskCommand.EnvEntryR\x03env\x12\x18\n" +
	"\acommand\x18\x16 \x03(\tR\acommand\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x17 \x03(\tR\n" +
	"entrypoint\x128\n" +
	"\avolumes\x18\x18 \x03(\v2\x1e.edgepilot.grpcapi.VolumeMountR\avolumes\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x03\n" +
	"\n" +
	"TaskUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.edgepilot.grpcapi.TaskStatusR\x06status\x12\x12\n" +
	"\x04step\x18\x03 \x01(\tR\x04step\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12!\n" +
	"\fcontainer_id\x18\x05 \x01(\tR\vcontainerId\x12%\n" +
	"\x0elisten_address\x18\x06 \x01(\tR\rlistenAddress\x12+\n" +
	"\x04slot\x18\a \x01(\x0e2\x17.edgepilot.grpcapi.SlotR\x04slot\x12\x1f\n" +
	"\vserver_name\x18\b \x01(\tR\n" +
	"serverName\x12D\n" +
	"\ametrics\x18\t \x03(\v2*.edgepilot.grpcapi.TaskUpdate.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xab\x03\n" +
	"\x12ProxyServiceConfig\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vservice_key\x18\x02 \x01(\tR\n" +
	"serviceKey\x12\x1d\n" +
	"\n" +
	"route_host\x18\x03 \x01(\tR\trouteHost\x12*\n" +
	"\x11route_path_prefix\x18\x04 \x01(\tR\x0froutePathPrefix\x12!\n" +
	"\fbackend_name\x18\x05 \x01(\tR\vbackendName\x12(\n" +
	"\x10blue_server_name\x18\x06 \x01(\tR\x0eblueServerName\x12*\n" +
	"\x11green_server_name\x18\a \x01(\tR\x0fgreenServerName\x12$\n" +
	"\x0eblue_host_port\x18\b \x01(\x05R\fblueHostPort\x12&\n" +
	"\x0fgreen_host_port\x18\t \x01(\x05R\rgreenHostPort\x12C\n" +
	"\x11current_live_slot\x18\n" +
	" \x01(\x0e2\x17.edgepilot.grpcapi.SlotR\x0fcurrentLiveSlot\"\xde\x01\n" +
	"\x13ProxyConfigSnapshot\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rfrontend_name\x18\x02 \x01(\tR\ffrontendName\x12'\n" +
	"\x0fdefault_backend\x18\x03 \x01(\tR\x0edefaultBackend\x12\x1b\n" +
	"\tbind_port\x18\x04 \x01(\x05R\bbindPort\x12A\n" +
	"\bservices\x18\x05 \x03(\v2%.edgepilot.grpcapi.ProxyServiceConfigR\bservices\"\xc4\x01\n" +
	"\x10BackendStatPoint\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fbackend_name\x18\x02 \x01(\tR\vbackendName\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04scur\x18\x04 \x01(\x03R\x04scur\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x03R\x04rate\x12%\n" +
	"\x0eerror_requests\x18\x06 \x01(\x03R\rerrorRequests\"i\n" +
	"\vStatsReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12?\n" +
	"\bservices\x18\x02 \x03(\v2#.edgepilot.grpcapi.BackendStatPointR\bservices*;\n" +
	"\x04Slot\x12\x14\n" +
	"\x10SLOT_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSLOT_BLUE\x10\x01\x12\x0e\n" +
	"\n" +
	"SLOT_GREEN\x10\x02*\x92\x01\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TASK_TYPE_DEPLOY_GREEN\x10\x01\x12\x1c\n" +
	"\x18TASK_TYPE_SWITCH_TRAFFIC\x10\x02\x12\x16\n" +
	"\x12TASK_TYPE_ROLLBACK\x10\x03\x12\x19\n" +
	"\x15TASK_TYPE_CLEANUP_OLD\x10\x04*u\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x01\x12\x19\n" +
	"\x15TASK_STATUS_SUCCEEDED\x10\x02\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x032a\n" +
	"\fAgentControl\x12Q\n" +
	"\aConnect\x12\x1f.edgepilot.grpcapi.AgentMessage\x1a!.edgepilot.grpcapi.ControlMessage(\x010\x01B,Z*edge-pilot/internal/shared/grpcapi;grpcapib\x06proto3"

var (
	file_internal_shared_grpcapi_agent_control_proto_rawDescOnce sync.Once
	file_internal_shared_grpcapi_agent_control_proto_rawDescData []byte
)

func file_internal_shared_grpcapi_agent_control_proto_rawDescGZIP() []byte {
	file_internal_shared_grpcapi_agent_control_proto_rawDescOnce.Do(func() {
		file_internal_shared_grpcapi_agent_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_shared_grpcapi_agent_control_proto_rawDesc), len(file_internal_shared_grpcapi_agent_control_proto_rawDesc)))
	})
	return file_internal_shared_grpcapi_agent_control_proto_rawDescData
}

var file_internal_shared_grpcapi_agent_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_shared_grpcapi_agent_control_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_shared_grpcapi_agent_control_proto_goTypes = []any{
	(Slot)(0),                   // 0: edgepilot.grpcapi.Slot
	(TaskType)(0),               // 1: edgepilot.grpcapi.TaskType
	(TaskStatus)(0),             // 2: edgepilot.grpcapi.TaskStatus
	(*AgentMessage)(nil),        // 3: edgepilot.grpcapi.AgentMessage
	(*ControlMessage)(nil),      // 4: edgepilot.grpcapi.ControlMessage
	(*HelloMessage)(nil),        // 5: edgepilot.grpcapi.HelloMessage
	(*HeartbeatMessage)(nil),    // 6: edgepilot.grpcapi.HeartbeatMessage
	(*AckMessage)(nil),          // 7: edgepilot.grpcapi.AckMessage
	(*VolumeMount)(nil),         // 8: edgepilot.grpcapi.VolumeMount
	(*TaskCommand)(nil),         // 9: edgepilot.grpcapi.TaskCommand
	(*TaskUpdate)(nil),          // 10: edgepilot.grpcapi.TaskUpdate
	(*ProxyServiceConfig)(nil),  // 11: edgepilot.grpcapi.ProxyServiceConfig
	(*ProxyConfigSnapshot)(nil), // 12: edgepilot.grpcapi.ProxyConfigSnapshot
	(*BackendStatPoint)(nil),    // 13: edgepilot.grpcapi.BackendStatPoint
	(*StatsReport)(nil),         // 14: edgepilot.grpcapi.StatsReport
	nil,                         // 15: edgepilot.grpcapi.TaskCommand.EnvEntry
	nil,                         // 16: edgepilot.grpcapi.TaskUpdate.MetricsEntry
}
var file_internal_shared_grpcapi_agent_control_proto_depIdxs = []int32{
	5,  // 0: edgepilot.grpcapi.AgentMessage.hello:type_name -> edgepilot.grpcapi.HelloMessage
	6,  // 1: edgepilot.grpcapi.AgentMessage.heartbeat:type_name -> edgepilot.grpcapi.HeartbeatMessage
	10, // 2: edgepilot.grpcapi.AgentMessage.task_update:type_name -> edgepilot.grpcapi.TaskUpdate
	14, // 3: edgepilot.grpcapi.AgentMessage.stats:type_name -> edgepilot.grpcapi.StatsReport
	7,  // 4: edgepilot.grpcapi.ControlMessage.ack:type_name -> edgepilot.grpcapi.AckMessage
	9,  // 5: edgepilot.grpcapi.ControlMessage.task:type_name -> edgepilot.grpcapi.TaskCommand
	12, // 6: edgepilot.grpcapi.ControlMessage.proxy_config:type_name -> edgepilot.grpcapi.ProxyConfigSnapshot
	1,  // 7: edgepilot.grpcapi.TaskCommand.type:type_name -> edgepilot.grpcapi.TaskType
	0,  // 8: edgepilot.grpcapi.TaskCommand.target_slot:type_name -> edgepilot.grpcapi.Slot
	0,  // 9: edgepilot.grpcapi.TaskCommand.current_live_slot:type_name -> edgepilot.grpcapi.Slot
	15, // 10: edgepilot.grpcapi.TaskCommand.env:type_name -> edgepilot.grpcapi.TaskCommand.EnvEntry
	8,  // 11: edgepilot.grpcapi.TaskCommand.volumes:type_name -> edgepilot.grpcapi.VolumeMount
	2,  // 12: edgepilot.grpcapi.TaskUpdate.status:type_name -> edgepilot.grpcapi.TaskStatus
	0,  // 13: edgepilot.grpcapi.TaskUpdate.slot:type_name -> edgepilot.grpcapi.Slot
	16, // 14: edgepilot.grpcapi.TaskUpdate.metrics:type_name -> edgepilot.grpcapi.TaskUpdate.MetricsEntry
	0,  // 15: edgepilot.grpcapi.ProxyServiceConfig.current_live_slot:type_name -> edgepilot.grpcapi.Slot
	11, // 16: edgepilot.grpcapi.ProxyConfigSnapshot.services:type_name -> edgepilot.grpcapi.ProxyServiceConfig
	13, // 17: edgepilot.grpcapi.StatsReport.services:type_name -> edgepilot.grpcapi.BackendStatPoint
	3,  // 18: edgepilot.grpcapi.AgentControl.Connect:input_type -> edgepilot.grpcapi.AgentMessage
	4,  // 19: edgepilot.grpcapi.AgentControl.Connect:output_type -> edgepilot.grpcapi.ControlMessage
	19, // [19:20] is the sub-list for method output_type
	18, // [18:19] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_internal_shared_grpcapi_agent_control_proto_init() }
func file_internal_shared_grpcapi_agent_control_proto_init() {
	if File_internal_shared_grpcapi_agent_control_proto != nil {
		return
	}
	file_internal_shared_grpcapi_agent_control_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_TaskUpdate)(nil),
		(*AgentMessage_Stats)(nil),
	}
	file_internal_shared_grpcapi_agent_control_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlMessage_Ack)(nil),
		(*ControlMessage_Task)(nil),
		(*ControlMessage_ProxyConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_shared_grpcapi_agent_control_proto_rawDesc), len(file_internal_shared_grpcapi_agent_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_shared_grpcapi_agent_control_proto_goTypes,
		DependencyIndexes: file_internal_shared_grpcapi_agent_control_proto_depIdxs,
		EnumInfos:         file_internal_shared_grpcapi_agent_control_proto_enumTypes,
		MessageInfos:      file_internal_shared_grpcapi_agent_control_proto_msgTypes,
	}.Build()
	File_internal_shared_grpcapi_agent_control_proto = out.File
	file_internal_shared_grpcapi_agent_control_proto_goTypes = nil
	file_internal_shared_grpcapi_agent_control_proto_depIdxs = nil
}
