// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: internal/shared/grpcapi/scheduler_control.proto

package grpcapi

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulerControl_Connect_FullMethodName = "/edgepilot.grpcapi.SchedulerControl/Connect"
)

// SchedulerControlClient is the client API for SchedulerControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerControlClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecutorMessage, SchedulerMessage], error)
}

type schedulerControlClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerControlClient(cc grpc.ClientConnInterface) SchedulerControlClient {
	return &schedulerControlClient{cc}
}

func (c *schedulerControlClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecutorMessage, SchedulerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SchedulerControl_ServiceDesc.Streams[0], SchedulerControl_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecutorMessage, SchedulerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchedulerControl_ConnectClient = grpc.BidiStreamingClient[ExecutorMessage, SchedulerMessage]

// SchedulerControlServer is the server API for SchedulerControl service.
// All implementations should embed UnimplementedSchedulerControlServer
// for forward compatibility.
type SchedulerControlServer interface {
	Connect(grpc.BidiStreamingServer[ExecutorMessage, SchedulerMessage]) error
}

// UnimplementedSchedulerControlServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerControlServer struct{}

func (UnimplementedSchedulerControlServer) Connect(grpc.BidiStreamingServer[ExecutorMessage, SchedulerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSchedulerControlServer) testEmbeddedByValue() {}

// UnsafeSchedulerControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerControlServer will
// result in compilation errors.
type UnsafeSchedulerControlServer interface {
	mustEmbedUnimplementedSchedulerControlServer()
}

func RegisterSchedulerControlServer(s grpc.ServiceRegistrar, srv SchedulerControlServer) {
	// If the following call panics, it indicates UnimplementedSchedulerControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerControl_ServiceDesc, srv)
}

func _SchedulerControl_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SchedulerControlServer).Connect(&grpc.GenericServerStream[ExecutorMessage, SchedulerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchedulerControl_ConnectServer = grpc.BidiStreamingServer[ExecutorMessage, SchedulerMessage]

// SchedulerControl_ServiceDesc is the grpc.ServiceDesc for SchedulerControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edgepilot.grpcapi.SchedulerControl",
	HandlerType: (*SchedulerControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _SchedulerControl_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/shared/grpcapi/scheduler_control.proto",
}

const (
	SchedulerInstanceControl_Attach_FullMethodName = "/edgepilot.grpcapi.SchedulerInstanceControl/Attach"
)

// SchedulerInstanceControlClient is the client API for SchedulerInstanceControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerInstanceControlClient interface {
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SchedulerInstanceMessage, SchedulerInstanceMessage], error)
}

type schedulerInstanceControlClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerInstanceControlClient(cc grpc.ClientConnInterface) SchedulerInstanceControlClient {
	return &schedulerInstanceControlClient{cc}
}

func (c *schedulerInstanceControlClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SchedulerInstanceMessage, SchedulerInstanceMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SchedulerInstanceControl_ServiceDesc.Streams[0], SchedulerInstanceControl_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SchedulerInstanceMessage, SchedulerInstanceMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchedulerInstanceControl_AttachClient = grpc.BidiStreamingClient[SchedulerInstanceMessage, SchedulerInstanceMessage]

// SchedulerInstanceControlServer is the server API for SchedulerInstanceControl service.
// All implementations should embed UnimplementedSchedulerInstanceControlServer
// for forward compatibility.
type SchedulerInstanceControlServer interface {
	Attach(grpc.BidiStreamingServer[SchedulerInstanceMessage, SchedulerInstanceMessage]) error
}

// UnimplementedSchedulerInstanceControlServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerInstanceControlServer struct{}

func (UnimplementedSchedulerInstanceControlServer) Attach(grpc.BidiStreamingServer[SchedulerInstanceMessage, SchedulerInstanceMessage]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedSchedulerInstanceControlServer) testEmbeddedByValue() {}

// UnsafeSchedulerInstanceControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerInstanceControlServer will
// result in compilation errors.
type UnsafeSchedulerInstanceControlServer interface {
	mustEmbedUnimplementedSchedulerInstanceControlServer()
}

func RegisterSchedulerInstanceControlServer(s grpc.ServiceRegistrar, srv SchedulerInstanceControlServer) {
	// If the following call panics, it indicates UnimplementedSchedulerInstanceControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerInstanceControl_ServiceDesc, srv)
}

func _SchedulerInstanceControl_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SchedulerInstanceControlServer).Attach(&grpc.GenericServerStream[SchedulerInstanceMessage, SchedulerInstanceMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchedulerInstanceControl_AttachServer = grpc.BidiStreamingServer[SchedulerInstanceMessage, SchedulerInstanceMessage]

// SchedulerInstanceControl_ServiceDesc is the grpc.ServiceDesc for SchedulerInstanceControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerInstanceControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edgepilot.grpcapi.SchedulerInstanceControl",
	HandlerType: (*SchedulerInstanceControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _SchedulerInstanceControl_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/shared/grpcapi/scheduler_control.proto",
}
