// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/shared/grpcapi/scheduler_control.proto

package grpcapi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecutorMessage_Hello
	//	*ExecutorMessage_Heartbeat
	//	*ExecutorMessage_RunUpdate
	//	*ExecutorMessage_LeaseRenew
	Payload       isExecutorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorMessage) Reset() {
	*x = ExecutorMessage{}
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorMessage) ProtoMessage() {}

func (x *ExecutorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorMessage.ProtoReflect.Descriptor instead.
func (*ExecutorMessage) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutorMessage) GetPayload() isExecutorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutorMessage) GetHello() *ExecutorHello {
	if x != nil {
		if x, ok := x.Payload.(*ExecutorMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ExecutorMessage) GetHeartbeat() *ExecutorHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ExecutorMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ExecutorMessage) GetRunUpdate() *SchedulerRunUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ExecutorMessage_RunUpdate); ok {
			return x.RunUpdate
		}
	}
	return nil
}

func (x *ExecutorMessage) GetLeaseRenew() *SchedulerRunLeaseRenew {
	if x != nil {
		if x, ok := x.Payload.(*ExecutorMessage_LeaseRenew); ok {
			return x.LeaseRenew
		}
	}
	return nil
}

type isExecutorMessage_Payload interface {
	isExecutorMessage_Payload()
}

type ExecutorMessage_Hello struct {
	Hello *ExecutorHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ExecutorMessage_Heartbeat struct {
	Heartbeat *ExecutorHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ExecutorMessage_RunUpdate struct {
	RunUpdate *SchedulerRunUpdate `protobuf:"bytes,3,opt,name=run_update,json=runUpdate,proto3,oneof"`
}

type ExecutorMessage_LeaseRenew struct {
	LeaseRenew *SchedulerRunLeaseRenew `protobuf:"bytes,4,opt,name=lease_renew,json=leaseRenew,proto3,oneof"`
}

func (*ExecutorMessage_Hello) isExecutorMessage_Payload() {}

func (*ExecutorMessage_Heartbeat) isExecutorMessage_Payload() {}

func (*ExecutorMessage_RunUpdate) isExecutorMessage_Payload() {}

func (*ExecutorMessage_LeaseRenew) isExecutorMessage_Payload() {}

type SchedulerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SchedulerMessage_Ack
	//	*SchedulerMessage_Run
	Payload       isSchedulerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerMessage) Reset() {
	*x = SchedulerMessage{}
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerMessage) ProtoMessage() {}

func (x *SchedulerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerMessage.ProtoReflect.Descriptor instead.
func (*SchedulerMessage) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulerMessage) GetPayload() isSchedulerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SchedulerMessage) GetAck() *SchedulerAck {
	if x != nil {
		if x, ok := x.Payload.(*SchedulerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *SchedulerMessage) GetRun() *SchedulerRunCommand {
	if x != nil {
		if x, ok := x.Payload.(*SchedulerMessage_Run); ok {
			return x.Run
		}
	}
	return nil
}

type isSchedulerMessage_Payload interface {
	isSchedulerMessage_Payload()
}

type SchedulerMessage_Ack struct {
	Ack *SchedulerAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type SchedulerMessage_Run struct {
	Run *SchedulerRunCommand `protobuf:"bytes,2,opt,name=run,proto3,oneof"`
}

func (*SchedulerMessage_Ack) isSchedulerMessage_Payload() {}

func (*SchedulerMessage_Run) isSchedulerMessage_Payload() {}

type ExecutorHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	LiveSlot      Slot                   `protobuf:"varint,4,opt,name=live_slot,json=liveSlot,proto3,enum=edgepilot.grpcapi.Slot" json:"live_slot,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Relay         string                 `protobuf:"bytes,6,opt,name=relay,proto3" json:"relay,omitempty"`
	RoutingKey    string                 `protobuf:"bytes,7,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorHello) Reset() {
	*x = ExecutorHello{}
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorHello) ProtoMessage() {}

func (x *ExecutorHello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorHello.ProtoReflect.Descriptor instead.
func (*ExecutorHello) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutorHello) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *ExecutorHello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ExecutorHello) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ExecutorHello) GetLiveSlot() Slot {
	if x != nil {
		return x.LiveSlot
	}
	return Slot_SLOT_UNSPECIFIED
}

func (x *ExecutorHello) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecutorHello) GetRelay() string {
	if x != nil {
		return x.Relay
	}
	return ""
}

func (x *ExecutorHello) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

type ExecutorHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	RunningRunIds []string               `protobuf:"bytes,2,rep,name=running_run_ids,json=runningRunIds,proto3" json:"running_run_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorHeartbeat) Reset() {
	*x = ExecutorHeartbeat{}
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorHeartbeat) ProtoMessage() {}

func (x *ExecutorHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorHeartbeat.ProtoReflect.Descriptor instead.
func (*ExecutorHeartbeat) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutorHeartbeat) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *ExecutorHeartbeat) GetRunningRunIds() []string {
	if x != nil {
		return x.RunningRunIds
	}
	return nil
}

type SchedulerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerAck) Reset() {
	*x = SchedulerAck{}
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerAck) ProtoMessage() {}

func (x *SchedulerAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerAck.ProtoReflect.Descriptor instead.
func (*SchedulerAck) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP(), []int{4}
}

func (x *SchedulerAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SchedulerRunCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	JobId          string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskType       string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Attempt        int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	PayloadJson    string                 `protobuf:"bytes,6,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchedulerRunCommand) Reset() {
	*x = SchedulerRunCommand{}
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerRunCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerRunCommand) ProtoMessage() {}

func (x *SchedulerRunCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerRunCommand.ProtoReflect.Descriptor instead.
func (*SchedulerRunCommand) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP(), []int{5}
}

func (x *SchedulerRunCommand) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SchedulerRunCommand) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SchedulerRunCommand) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *SchedulerRunCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SchedulerRunCommand) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *SchedulerRunCommand) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SchedulerRunUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Running       bool                   `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerRunUpdate) Reset() {
	*x = SchedulerRunUpdate{}
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerRunUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerRunUpdate) ProtoMessage() {}

func (x *SchedulerRunUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerRunUpdate.ProtoReflect.Descriptor instead.
func (*SchedulerRunUpdate) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP(), []int{6}
}

func (x *SchedulerRunUpdate) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SchedulerRunUpdate) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SchedulerRunUpdate) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *SchedulerRunUpdate) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SchedulerRunUpdate) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

type SchedulerRunLeaseRenew struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerRunLeaseRenew) Reset() {
	*x = SchedulerRunLeaseRenew{}
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerRunLeaseRenew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerRunLeaseRenew) ProtoMessage() {}

func (x *SchedulerRunLeaseRenew) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerRunLeaseRenew.ProtoReflect.Descriptor instead.
func (*SchedulerRunLeaseRenew) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP(), []int{7}
}

func (x *SchedulerRunLeaseRenew) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type SchedulerInstanceMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SchedulerInstanceMessage_Attach
	//	*SchedulerInstanceMessage_Heartbeat
	//	*SchedulerInstanceMessage_Run
	//	*SchedulerInstanceMessage_RunUpdate
	//	*SchedulerInstanceMessage_LeaseRenew
	//	*SchedulerInstanceMessage_Ack
	Payload       isSchedulerInstanceMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerInstanceMessage) Reset() {
	*x = SchedulerInstanceMessage{}
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerInstanceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerInstanceMessage) ProtoMessage() {}

func (x *SchedulerInstanceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerInstanceMessage.ProtoReflect.Descriptor instead.
func (*SchedulerInstanceMessage) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP(), []int{8}
}

func (x *SchedulerInstanceMessage) GetPayload() isSchedulerInstanceMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SchedulerInstanceMessage) GetAttach() *SchedulerInstanceAttach {
	if x != nil {
		if x, ok := x.Payload.(*SchedulerInstanceMessage_Attach); ok {
			return x.Attach
		}
	}
	return nil
}

func (x *SchedulerInstanceMessage) GetHeartbeat() *ExecutorHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*SchedulerInstanceMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *SchedulerInstanceMessage) GetRun() *SchedulerRunCommand {
	if x != nil {
		if x, ok := x.Payload.(*SchedulerInstanceMessage_Run); ok {
			return x.Run
		}
	}
	return nil
}

func (x *SchedulerInstanceMessage) GetRunUpdate() *SchedulerRunUpdate {
	if x != nil {
		if x, ok := x.Payload.(*SchedulerInstanceMessage_RunUpdate); ok {
			return x.RunUpdate
		}
	}
	return nil
}

func (x *SchedulerInstanceMessage) GetLeaseRenew() *SchedulerRunLeaseRenew {
	if x != nil {
		if x, ok := x.Payload.(*SchedulerInstanceMessage_LeaseRenew); ok {
			return x.LeaseRenew
		}
	}
	return nil
}

func (x *SchedulerInstanceMessage) GetAck() *SchedulerAck {
	if x != nil {
		if x, ok := x.Payload.(*SchedulerInstanceMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isSchedulerInstanceMessage_Payload interface {
	isSchedulerInstanceMessage_Payload()
}

type SchedulerInstanceMessage_Attach struct {
	Attach *SchedulerInstanceAttach `protobuf:"bytes,1,opt,name=attach,proto3,oneof"`
}

type SchedulerInstanceMessage_Heartbeat struct {
	Heartbeat *ExecutorHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type SchedulerInstanceMessage_Run struct {
	Run *SchedulerRunCommand `protobuf:"bytes,3,opt,name=run,proto3,oneof"`
}

type SchedulerInstanceMessage_RunUpdate struct {
	RunUpdate *SchedulerRunUpdate `protobuf:"bytes,4,opt,name=run_update,json=runUpdate,proto3,oneof"`
}

type SchedulerInstanceMessage_LeaseRenew struct {
	LeaseRenew *SchedulerRunLeaseRenew `protobuf:"bytes,5,opt,name=lease_renew,json=leaseRenew,proto3,oneof"`
}

type SchedulerInstanceMessage_Ack struct {
	Ack *SchedulerAck `protobuf:"bytes,6,opt,name=ack,proto3,oneof"`
}

func (*SchedulerInstanceMessage_Attach) isSchedulerInstanceMessage_Payload() {}

func (*SchedulerInstanceMessage_Heartbeat) isSchedulerInstanceMessage_Payload() {}

func (*SchedulerInstanceMessage_Run) isSchedulerInstanceMessage_Payload() {}

func (*SchedulerInstanceMessage_RunUpdate) isSchedulerInstanceMessage_Payload() {}

func (*SchedulerInstanceMessage_LeaseRenew) isSchedulerInstanceMessage_Payload() {}

func (*SchedulerInstanceMessage_Ack) isSchedulerInstanceMessage_Payload() {}

type SchedulerInstanceAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceKey    string                 `protobuf:"bytes,3,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"`
	ReleaseId     string                 `protobuf:"bytes,4,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Slot          Slot                   `protobuf:"varint,5,opt,name=slot,proto3,enum=edgepilot.grpcapi.Slot" json:"slot,omitempty"`
	Group         string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	ContainerId   string                 `protobuf:"bytes,7,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerInstanceAttach) Reset() {
	*x = SchedulerInstanceAttach{}
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerInstanceAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerInstanceAttach) ProtoMessage() {}

func (x *SchedulerInstanceAttach) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerInstanceAttach.ProtoReflect.Descriptor instead.
func (*SchedulerInstanceAttach) Descriptor() ([]byte, []int) {
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP(), []int{9}
}

func (x *SchedulerInstanceAttach) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *SchedulerInstanceAttach) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SchedulerInstanceAttach) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

func (x *SchedulerInstanceAttach) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *SchedulerInstanceAttach) GetSlot() Slot {
	if x != nil {
		return x.Slot
	}
	return Slot_SLOT_UNSPECIFIED
}

func (x *SchedulerInstanceAttach) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SchedulerInstanceAttach) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

var File_internal_shared_grpcapi_scheduler_control_proto protoreflect.FileDescriptor

const file_internal_shared_grpcapi_scheduler_control_proto_rawDesc = "" +
	"\n" +
	"/internal/shared/grpcapi/scheduler_control.proto\x12\x11edgepilot.grpcapi\x1a+internal/shared/grpcapi/agent_control.proto\"\xb2\x02\n" +
	"\x0fExecutorMessage\x128\n" +
	"\x05hello\x18\x01 \x01(\v2 .edgepilot.grpcapi.ExecutorHelloH\x00R\x05hello\x12D\n" +
	"\theartbeat\x18\x02 \x01(\v2$.edgepilot.grpcapi.ExecutorHeartbeatH\x00R\theartbeat\x12F\n" +
	"\n" +
	"run_update\x18\x03 \x01(\v2%.edgepilot.grpcapi.SchedulerRunUpdateH\x00R\trunUpdate\x12L\n" +
	"\vlease_renew\x18\x04 \x01(\v2).edgepilot.grpcapi.SchedulerRunLeaseRenewH\x00R\n" +
	"leaseRenewB\t\n" +
	"\apayload\"\x8e\x01\n" +
	"\x10SchedulerMessage\x123\n" +
	"\x03ack\x18\x01 \x01(\v2\x1f.edgepilot.grpcapi.SchedulerAckH\x00R\x03ack\x12:\n" +
	"\x03run\x18\x02 \x01(\v2&.edgepilot.grpcapi.SchedulerRunCommandH\x00R\x03runB\t\n" +
	"\apayload\"\xd2\x02\n" +
	"\rExecutorHello\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x124\n" +
	"\tlive_slot\x18\x04 \x01(\x0e2\x17.edgepilot.grpcapi.SlotR\bliveSlot\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..edgepilot.grpcapi.ExecutorHello.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05relay\x18\x06 \x01(\tR\x05relay\x12\x1f\n" +
	"\vrouting_key\x18\a \x01(\tR\n" +
	"routingKey\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x11ExecutorHeartbeat\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12&\n" +
	"\x0frunning_run_ids\x18\x02 \x03(\tR\rrunningRunIds\"(\n" +
	"\fSchedulerAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc6\x01\n" +
	"\x13SchedulerRunCommand\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12!\n" +
	"\fpayload_json\x18\x06 \x01(\tR\vpayloadJson\"\xa2\x01\n" +
	"\x12SchedulerRunUpdate\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\arunning\x18\x05 \x01(\bR\arunning\"/\n" +
	"\x16SchedulerRunLeaseRenew\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xb8\x03\n" +
	"\x18SchedulerInstanceMessage\x12D\n" +
	"\x06attach\x18\x01 \x01(\v2*.edgepilot.grpcapi.SchedulerInstanceAttachH\x00R\x06attach\x12D\n" +
	"\theartbeat\x18\x02 \x01(\v2$.edgepilot.grpcapi.ExecutorHeartbeatH\x00R\theartbeat\x12:\n" +
	"\x03run\x18\x03 \x01(\v2&.edgepilot.grpcapi.SchedulerRunCommandH\x00R\x03run\x12F\n" +
	"\n" +
	"run_update\x18\x04 \x01(\v2%.edgepilot.grpcapi.SchedulerRunUpdateH\x00R\trunUpdate\x12L\n" +
	"\vlease_renew\x18\x05 \x01(\v2).edgepilot.grpcapi.SchedulerRunLeaseRenewH\x00R\n" +
	"leaseRenew\x123\n" +
	"\x03ack\x18\x06 \x01(\v2\x1f.edgepilot.grpcapi.SchedulerAckH\x00R\x03ackB\t\n" +
	"\apayload\"\xff\x01\n" +
	"\x17SchedulerInstanceAttach\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vservice_key\x18\x03 \x01(\tR\n" +
	"serviceKey\x12\x1d\n" +
	"\n" +
	"release_id\x18\x04 \x01(\tR\treleaseId\x12+\n" +
	"\x04slot\x18\x05 \x01(\x0e2\x17.edgepilot.grpcapi.SlotR\x04slot\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12!\n" +
	"\fcontainer_id\x18\a \x01(\tR\vcontainerId2j\n" +
	"\x10SchedulerControl\x12V\n" +
	"\aConnect\x12\".edgepilot.grpcapi.ExecutorMessage\x1a#.edgepilot.grpcapi.SchedulerMessage(\x010\x012\x82\x01\n" +
	"\x18SchedulerInstanceControl\x12f\n" +
	"\x06Attach\x12+.edgepilot.grpcapi.SchedulerInstanceMessage\x1a+.edgepilot.grpcapi.SchedulerInstanceMessage(\x010\x01B,Z*edge-pilot/internal/shared/grpcapi;grpcapib\x06proto3"

var (
	file_internal_shared_grpcapi_scheduler_control_proto_rawDescOnce sync.Once
	file_internal_shared_grpcapi_scheduler_control_proto_rawDescData []byte
)

func file_internal_shared_grpcapi_scheduler_control_proto_rawDescGZIP() []byte {
	file_internal_shared_grpcapi_scheduler_control_proto_rawDescOnce.Do(func() {
		file_internal_shared_grpcapi_scheduler_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_shared_grpcapi_scheduler_control_proto_rawDesc), len(file_internal_shared_grpcapi_scheduler_control_proto_rawDesc)))
	})
	return file_internal_shared_grpcapi_scheduler_control_proto_rawDescData
}

var file_internal_shared_grpcapi_scheduler_control_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_shared_grpcapi_scheduler_control_proto_goTypes = []any{
	(*ExecutorMessage)(nil),          // 0: edgepilot.grpcapi.ExecutorMessage
	(*SchedulerMessage)(nil),         // 1: edgepilot.grpcapi.SchedulerMessage
	(*ExecutorHello)(nil),            // 2: edgepilot.grpcapi.ExecutorHello
	(*ExecutorHeartbeat)(nil),        // 3: edgepilot.grpcapi.ExecutorHeartbeat
	(*SchedulerAck)(nil),             // 4: edgepilot.grpcapi.SchedulerAck
	(*SchedulerRunCommand)(nil),      // 5: edgepilot.grpcapi.SchedulerRunCommand
	(*SchedulerRunUpdate)(nil),       // 6: edgepilot.grpcapi.SchedulerRunUpdate
	(*SchedulerRunLeaseRenew)(nil),   // 7: edgepilot.grpcapi.SchedulerRunLeaseRenew
	(*SchedulerInstanceMessage)(nil), // 8: edgepilot.grpcapi.SchedulerInstanceMessage
	(*SchedulerInstanceAttach)(nil),  // 9: edgepilot.grpcapi.SchedulerInstanceAttach
	nil,                              // 10: edgepilot.grpcapi.ExecutorHello.MetadataEntry
	(Slot)(0),                        // 11: edgepilot.grpcapi.Slot
}
var file_internal_shared_grpcapi_scheduler_control_proto_depIdxs = []int32{
	2,  // 0: edgepilot.grpcapi.ExecutorMessage.hello:type_name -> edgepilot.grpcapi.ExecutorHello
	3,  // 1: edgepilot.grpcapi.ExecutorMessage.heartbeat:type_name -> edgepilot.grpcapi.ExecutorHeartbeat
	6,  // 2: edgepilot.grpcapi.ExecutorMessage.run_update:type_name -> edgepilot.grpcapi.SchedulerRunUpdate
	7,  // 3: edgepilot.grpcapi.ExecutorMessage.lease_renew:type_name -> edgepilot.grpcapi.SchedulerRunLeaseRenew
	4,  // 4: edgepilot.grpcapi.SchedulerMessage.ack:type_name -> edgepilot.grpcapi.SchedulerAck
	5,  // 5: edgepilot.grpcapi.SchedulerMessage.run:type_name -> edgepilot.grpcapi.SchedulerRunCommand
	11, // 6: edgepilot.grpcapi.ExecutorHello.live_slot:type_name -> edgepilot.grpcapi.Slot
	10, // 7: edgepilot.grpcapi.ExecutorHello.metadata:type_name -> edgepilot.grpcapi.ExecutorHello.MetadataEntry
	9,  // 8: edgepilot.grpcapi.SchedulerInstanceMessage.attach:type_name -> edgepilot.grpcapi.SchedulerInstanceAttach
	3,  // 9: edgepilot.grpcapi.SchedulerInstanceMessage.heartbeat:type_name -> edgepilot.grpcapi.ExecutorHeartbeat
	5,  // 10: edgepilot.grpcapi.SchedulerInstanceMessage.run:type_name -> edgepilot.grpcapi.SchedulerRunCommand
	6,  // 11: edgepilot.grpcapi.SchedulerInstanceMessage.run_update:type_name -> edgepilot.grpcapi.SchedulerRunUpdate
	7,  // 12: edgepilot.grpcapi.SchedulerInstanceMessage.lease_renew:type_name -> edgepilot.grpcapi.SchedulerRunLeaseRenew
	4,  // 13: edgepilot.grpcapi.SchedulerInstanceMessage.ack:type_name -> edgepilot.grpcapi.SchedulerAck
	11, // 14: edgepilot.grpcapi.SchedulerInstanceAttach.slot:type_name -> edgepilot.grpcapi.Slot
	0,  // 15: edgepilot.grpcapi.SchedulerControl.Connect:input_type -> edgepilot.grpcapi.ExecutorMessage
	8,  // 16: edgepilot.grpcapi.SchedulerInstanceControl.Attach:input_type -> edgepilot.grpcapi.SchedulerInstanceMessage
	1,  // 17: edgepilot.grpcapi.SchedulerControl.Connect:output_type -> edgepilot.grpcapi.SchedulerMessage
	8,  // 18: edgepilot.grpcapi.SchedulerInstanceControl.Attach:output_type -> edgepilot.grpcapi.SchedulerInstanceMessage
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_shared_grpcapi_scheduler_control_proto_init() }
func file_internal_shared_grpcapi_scheduler_control_proto_init() {
	if File_internal_shared_grpcapi_scheduler_control_proto != nil {
		return
	}
	file_internal_shared_grpcapi_agent_control_proto_init()
	file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecutorMessage_Hello)(nil),
		(*ExecutorMessage_Heartbeat)(nil),
		(*ExecutorMessage_RunUpdate)(nil),
		(*ExecutorMessage_LeaseRenew)(nil),
	}
	file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[1].OneofWrappers = []any{
		(*SchedulerMessage_Ack)(nil),
		(*SchedulerMessage_Run)(nil),
	}
	file_internal_shared_grpcapi_scheduler_control_proto_msgTypes[8].OneofWrappers = []any{
		(*SchedulerInstanceMessage_Attach)(nil),
		(*SchedulerInstanceMessage_Heartbeat)(nil),
		(*SchedulerInstanceMessage_Run)(nil),
		(*SchedulerInstanceMessage_RunUpdate)(nil),
		(*SchedulerInstanceMessage_LeaseRenew)(nil),
		(*SchedulerInstanceMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_shared_grpcapi_scheduler_control_proto_rawDesc), len(file_internal_shared_grpcapi_scheduler_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_shared_grpcapi_scheduler_control_proto_goTypes,
		DependencyIndexes: file_internal_shared_grpcapi_scheduler_control_proto_depIdxs,
		MessageInfos:      file_internal_shared_grpcapi_scheduler_control_proto_msgTypes,
	}.Build()
	File_internal_shared_grpcapi_scheduler_control_proto = out.File
	file_internal_shared_grpcapi_scheduler_control_proto_goTypes = nil
	file_internal_shared_grpcapi_scheduler_control_proto_depIdxs = nil
}
